### ISSUE TITLE
protocol = dmrgateway

### ISSUE THREAD

**Issue by picchiosat** [OK-DMR/Hytera_Homebrew_Bridge#14] opened 2021-11-28 22:25 UTC
Hi all, I'm testing HHB with an RD625.
With the "dmrgateway" protocol the latest version of Jonathan's software does NOT work.
I have installed version 4.2020 and using the "mmdvm" protocol everything works fine.
From the analysis of the DMRGateway log it seems that HHB in "dmrgateway mode" does not transmit the correct login information but remains in mmdvm mode.

Roby, IV3JDV

**Comment by smarek** [comment] 2022-02-18 21:12
Thanks, i'm aware of this issue, it is already described in #8
Closing as duplicate of #8

**Closed by smarek** 2022-02-18 21:12 UTC
